name: Fetch Sheets and Build CSVs (15:05 HKT)
permissions:
  contents: write

on:
  schedule:
    # GitHub uses UTC; 15:05 HKT = 07:05 UTC (Mon–Fri)
    - cron: "5 7 * * 1-5"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests numpy pytz

      - name: Fetch and merge
        env:
          TZ: Asia/Hong_Kong
        run: |
          python scripts/fetch_and_merge.py

           - name: Commit outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          # 用「已暫存」變更判斷（或比較 HEAD）
          if ! git diff --staged --quiet; then
            git commit -m "auto: update data CSVs"
            git push
          else
            echo "No changes to commit."
          fi
